export const afghans = [
    {
        id: 1,
        title: "Stained Glass Afghan",
        img: "img/stainedglassafghan.jpg",
        price: 150,
        info:"Measures approximately 45 x 60 inches.",
        credits: "Pattern Source: Annie's Crochet 885109",
        color: false,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 2,
        title: "Peace Sign Afghan",
        img: "img/peacesignafghan.jpg",
        price: 140,
        info:"Measures approximately 48 x 70 inches.",
        credits: "Designed by JudyK - Published in So Far, So Good.",
        color: false,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 3,
        title: "Zebra Afghan",
        img: "img/zebraafghan.jpg",
        price: 160,
        info:"Measures approximately 46 x 61 inches.",
        credits: "Pattern Source: Annie's Crochet Newsletter Nov-Dec 1990",
        color: false,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 4,
        title: "Kaleidoscope Eyes Blanket",
        img: "img/kaleidoscopeeyesblanket.jpg",
        price: 100,
        info:"Measures approximately 39 x 51 inches.",
        credits: "Designed by FeltedButton.com",
        color: false,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 5,
        title: "Christmas Afghan",
        img: "img/Christas Afghan.jpg",
        price: 100,
        info:"Measures approximately 56 x 72 inches.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 6,
        title: "Basketweave Afghan",
        img: "img/basketweaveafghan.jpg",
        price: 145,
        info:"Afghan in a Basketweave pattern. It is a little bit heavier than the regular afghans.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 7,
        title: "Climbing Rose Lace Afghan",
        img: "img/climbingroseafghan.jpg",
        price: 175,
        info:"This afghan has lacy edges and panels. The rosebuds, stems, and leaves are embroidered on the afghan. Please specify the main color as white or off-white with your rose color preference.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 8,
        title: "Big Granny Square Afghan",
        img: "img/biggranny.jpg",
        price: 95,
        info:"This afghan has large and small squares to make this perfect Granny afghan.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 9,
        title: "Pineapple Square Afghan",
        img: "img/pineapplesquareafghan.jpg",
        price: 100,
        info:"Measures approximately 56 x 72 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 10,
        title: "Red and White Wavy Lapghan",
        img: "img/redandwhiteafghan.jpg",
        price: 85,
        info:"Measures approximately 36 x 54 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 11,
        title: "Peruvian Style Afghan",
        img: "img/peruvianstyleafghan.jpg",
        price: 125,
        info:"This is a simple Peruvian style afghan measuring 45 x 72 inches. Size can be adjusted by width or length. For custom size, send an email to Tobita. Additional charge for bigger size afghan will apply.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 12,
        title: "Irish Afghan",
        img: "img/aran_afghan.jpg",
        price: 145,
        info:"Measures approximately 45 x 85 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 13,
        title: "Granny Square Throw",
        img: "img/grannysquareafghan.jpg",
        price: 95,
        info:"Measures approximately 38 x 58 inches. A perfect throw to lounge and snuggle up with. Please specify color(s).",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 14,
        title: "Ripple Afghan",
        img: "img/ripple.jpg",
        price: 120,
        info:"Measures approximately 42 x 72 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 15,
        title: "Fisherman Ripple Afghan",
        img: "img/afghan.jpg",
        price: 120,
        info:"This Afghan is almost the same as the Black and Grey afghan except this one has some lacy effects in between some solid rows. Afghan measures approximately 48 x 75 inches, slightly longer than the Ripple Afghan.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 16,
        title: "Popcorn Diamond Square - Afghan",
        img: "img/bed.jpg",
        price: 150,
        info:"This type of afghan can be made custom size. The sample in the picture was made as a bedcover. The measurement for a regular size afghan is approximately 55 x 84 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 17,
        title: "Popcorn Diamond Square - Twin",
        img: "img/bed.jpg",
        price: 175,
        info:"This type of afghan can be made custom size. The sample in the picture was made as a bedcover. The measurement for a regular size afghan is approximately 55 x 84 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 18,
        title: "Popcorn Diamond Square - Double",
        img: "img/bed.jpg",
        price: 200,
        info:"This type of afghan can be made custom size. The sample in the picture was made as a bedcover. The measurement for a regular size afghan is approximately 55 x 84 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 19,
        title: "Popcorn Diamond Square - Queen",
        img: "img/bed.jpg",
        price: 225,
        info:"This type of afghan can be made custom size. The sample in the picture was made as a bedcover. The measurement for a regular size afghan is approximately 55 x 84 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 20,
        title: "Popcorn Diamond Square - King",
        img: "img/bed.jpg",
        price: 250,
        info:"This type of afghan can be made custom size. The sample in the picture was made as a bedcover. The measurement for a regular size afghan is approximately 55 x 84 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 21,
        title: "Circle of Squares Lapghan",
        img: "img/circlesquareafghan.jpg",
        price: 95,
        info:"This is a smaller afghan which measures approximately 38 x 54 inches.  The squares are in different colors...makes a wonderful gift!",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 22,
        title: "Pink Cluster Afghan",
        img: "img/pinkafghan.jpg",
        price: 125,
        info:"Afghan measures approximately 48 x 72 inches. Can be crocheted in any color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 23,
        title: "Simplistic Afghan",
        img: "img/yellowpinkafghan.jpg",
        price: 110,
        info:"Measures approximately 48 x 60 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 24,
        title: "Scrap Afghan",
        img: "img/scrapafghan.jpg",
        price: 100,
        info:"This afghan is crocheted with leftover yarn from other projects to create beautiful color cordinated squares. Afghan measures approximately 48 x 60 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
      }

];

export const bedcovers = [
    {
        id: 1,
        title: "Flower Square Bedcover - Twin",
        img: "img/bedcover.jpg",
        price: 250,
        info:"Crocheted with 100% mercerized cotton thread.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Flower Square Bedcover - Double",
        img: "img/bedcover.jpg",
        price: 350,
        info:"Crocheted with 100% mercerized cotton thread.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Flower Square Bedcover - Queen",
        img: "img/bedcover.jpg",
        price: 450,
        info:"Crocheted with 100% mercerized cotton thread.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Flower Square Bedcover - King",
        img: "img/bedcover.jpg",
        price: 550,
        info:"Crocheted with 100% mercerized cotton thread.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const babyAfghans = [
    {
        id: 1,
        title: "Multi Pastel Color Baby Afghan - LG",
        img: "img/babyafghan.jpg",
        price: 65,
        info:"Measures 40x50 inches. This baby afghan is crocheted with variegated baby pastel colors. If you want a solid color, please insert your color preference in the color box.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Multi Pastel Color Baby Afghan - SM",
        img: "img/babyafghan.jpg",
        price: 60,
        info:"Measures 36x48 inches. This baby afghan is crocheted with variegated baby pastel colors. If you want a solid color, please insert your color preference in the color box.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Feathery Lace Baby Afghan",
        img: "img/featherylacebabyafghan.jpg",
        price: 60,
        info:"Measures 38 1/2 x 52 inches. Washable and dryable.",
        credits: "Pattern Source: Ripples for Baby to Crochet by Leisure Arts",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Football and Baby Name Baby Afghan",
        img: "img/namefootball.jpg",
        price: 70,
        info:"Baby afghan with a football and your baby's name. You can leave out the football and have only your baby's name on the afghan. Measures approximately 36 x 48 inches (depending on the length of the name). Washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Small Squares Baby Afghan",
        img: "img/bsqafghan.jpg",
        price: 60,
        info:"This cute little baby afghan is crocheted with lots of tiny squares. Measures 32 x 44 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Pink & White Baby Afghan",
        img: "img/pinkbafghan.jpg",
        price: 60,
        info:"Measures approximately 36 x 48 inches. Washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        title: "Small Squares Baby Afghan - With Booties",
        img: "img/pinkbafghan.jpg",
        price: 65,
        info:"Measures approximately 36 x 48 inches. Washable and dryable. Includes pair of baby booties in matching color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 8,
        title: "Blue & White Baby Afghan",
        img: "img/blanket.jpg",
        price: 60,
        info:"Measures approximately 36 x 48 inches. Washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9,
        title: "Blue & White Baby Afghan - With Booties",
        img: "img/blanket.jpg",
        price: 65,
        info:"Measures approximately 36 x 48 inches. Washable and dryable. Includes pair of baby booties in matching color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10,
        title: "Crocheted Star Baby Quilt",
        img: "img/quilt.jpg",
        price: 85,
        info:"Baby afghan is crocheted and sewn like a real quilt! Measurements are approximately 36 x 48 inches. Washable and Dryable.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 11,
        title: "Rainbow Baby Afghan",
        img: "img/rainbow.jpg",
        price: 85,
        info:"Rainbows in a baby afghan.",
        credits: "Pattern design by Helen Free",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 12,
        title: "Granny Square Style Baby Afghan",
        img: "img/bluegrannybabyghan.jpg",
        price: 70,
        info:"Measures approximately 36 x 38 inches. Machine washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 13,
        title: "Baby Afghan",
        img: "img/binkt-br.jpg",
        price: 60,
        info:"Measures approximately 36 x 48 inches. Machine washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 14,
        title: "Baby Afghan - with Bear",
        img: "img/binkt-br.jpg",
        price: 70,
        info:"Measures approximately 36 x 48 inches. Machine washable and dryable. Includes teddy bear in matching color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const babyClothes = [
    {
        id: 1,
        title: "Baby Boy Outfit",
        img: "img/babyboyoutfit.jpg",
        price: 75,
        info:"A beautiful set for a Baby Boy. Set includes Pants, Sweater, Booties, and bonnett.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Open Crescent Baby Dress",
        img: "img/threadbabydress.jpg",
        price: 75,
        info:"A beautiful Pineapple Baby dress with open crescent skirt.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Pineapple Dress and Beret",
        img: "img/pineappledress.jpg",
        price: 95,
        info:"A beautiful Pineapple Baby dress with buttoned-back opening and beret.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Baby Tank Top and Undies",
        img: "img/babytankundies.jpg",
        price: 65,
        info:"A tank top and undies to use under a formal dress, pineapple dress, or use it alone.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Tiny Square Yoke Dress and Booties",
        img: "img/b-dress.jpg",
        price: 70,
        info:"See matching booties in Baby Shoes section.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Filet Baby Dress and Booties",
        img: "img/filetdress.jpg",
        price: 65,
        info:"Crocheted with fine cotton thread for those hot summer months.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        title: "Baby Layette Set",
        img: "img/babyset.jpg",
        price: 85,
        info:"Set includes Baby Afghan, Baby Sweater, and Baby Booties.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 8,
        title: "Two Color Dress and Booties",
        img: "img/ls-dress.jpg",
        price: 85,
        info:"Specify Top color and Skirt color",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9,
        title: "Pants & Sweater Combo",
        img: "img/pants-sweater.jpg",
        price: 65,
        info:"A comfortable drawstring pants and buttoned front sweater.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10,
        title: "Formal Baby Dress and Booties",
        img: "img/bwdress.jpg",
        price: 70,
        info:"A formal crochet dress with buttoned-back opening, underskirt fabric lining, and baby booties.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const babyBooties = [
    {
        id: 1,
        title: "Heart Embedded Baby Booties",
        img: "img/heartbabyshoes.jpg",
        price: 25,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Girl Skate Booties",
        img: "img/girlskates.jpg",
        price: 35,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Boy Skate Booties",
        img: "img/boyskates.jpg",
        price: 35,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Baby Booties",
        img: "img/bshoes.jpg",
        price: 20,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Tiny Square Yoke Baby Booties",
        img: "img/bbyshoe3.jpg",
        price: 25,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const bridal = [
    {
        id: 1,
        title: "Bridal Set",
        img: "img/bridalset.jpg",
        price: 95,
        info:"Beautiful Bridal set for the new Bride. Set includes Garter, Purse, Horseshoe, Ring Pillow, and Choker. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004. Pattern for sale at http://www.enfys.dsl.pipex.com",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Bridal Garter",
        img: "img/bridalgarter.jpg",
        price: 25,
        info:"Beautiful Bridal Garter for the bride. Garter is made with glittery seed beads to give it the classy elegant look. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Bridal Ring Pillow",
        img: "img/bridalringpillow.jpg",
        price: 25,
        info:"The Bridal Ring Pillow holds the couple's wedding rings. Made with glossy seed beads and satin fabric to give the pillow a classy elegant look. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Bridal Choker",
        img: "img/bridalchoker.jpg",
        price: 20,
        info:"Choker is made with glossy beads and ribbon for that classy elegant look. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Bridal Purse",
        img: "img/bridalpurse.jpg",
        price: 30,
        info:"Beautiful Bridal purse for the new Bride. Made with glossy seed beads and lined with satin fabric. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Bridal Horseshoe",
        img: "img/bridalhorseshoe.jpg",
        price: 25,
        info:"Start your tradition by giving the Bride a Horse Shoe for luck and fortune. Made with seed beads and ribbon. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }
    
];

export const christmas = [
    {
        id: 1,
        title: "Christmas Stocking",
        img: "img/bootstocking.jpg",
        price: 15,
        info:"Measures 16 inches in height. Beautiful Stocking to add to your Christmas decorations and holds lots of goodies! Specify main color and heel color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Crochet Christmas Creche",
        img: "img/crochetcreche.jpg",
        price: 95,
        info:"Measures from 3 to 9 inches in height. Beautiful Mary, Joseph, and Child Jesus set with animals to add to your Christmas display.",
        credits: "Pattern purchased from Annie's e-pattern central.",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Christmas Tree Skirt",
        img: "img/christmastreeskirt.jpg",
        price: 65,
        info:"Measures approximately 36 inches across.",
        credits: "Pattern from Love the Country website.",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Christmas Wreath",
        img: "img/christmaswreath.jpg",
        price: 85,
        info:"Measures approximately 14 inches across.",
        credits: "Pattern by Attic24",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Snowman",
        img: "img/snowman.jpg",
        price: 5,
        info:"Measures 4 inches in height. Beautiful ornament to add to your Christmas decorations.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Angel in Gold Dress",
        img: "img/gold-angel.jpg",
        price: 35,
        info:"Beautiful angel in a gold dress. Can be used as a tree topper or place anywhere in the home. Measures approximately 7 inches tall.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        title: "White Mini-Angel Tree Ornament",
        img: "img/miniangels.jpg",
        price: 1,
        info:"Measures approximately 3 inches in height.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 8,
        title: "Candy Cane Tree Ornament",
        img: "img/candycane.jpg",
        price: .75,
        info:"Measures approximately 3 inches in height. Specify red, white, or Christmas color blend.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9,
        title: "Christmas Tree",
        img: "img/g-tree.jpg",
        price: 15,
        info:"Measures approximately 7 inches tall. Decorated with available mini ornaments. Specify tree and bow color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10,
        title: "Angel",
        img: "img/angel2.jpg",
        price: 25,
        info:"This beautiful angel looks beautiful on top of the Christmas Tree or anywhere in your house. Measures approximately 7 inches tall. Specify dress and hair color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 11,
        title: "Mini Christmas Booties",
        img: "img/booties.jpg",
        price: 3,
        info:"Measures approximately 4 inches tall. Specify color. Buy two, get $1 off!",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 12,
        title: "Mini Christmas Baskets",
        img: "img/w-basket.jpg",
        price: 3,
        info:"Measures approximately 3 inches tall. Specify color. Buy two, get $1 off!",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 13,
        title: "Christmas Jingle Bells",
        img: "img/christmas-bells.jpg",
        price: 3,
        info:"Measures approximately 3 inches tall. Specify color. Buy two, get $1 off!",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 14,
        title: "Wine Christmas Covering",
        img: "img/christmaswinebottlecovers.jpg",
        price: 15,
        info:"Makes a wonderful impersonal gift. Measures approximately 7 inches high. Includes wine or it can be replaced with other similar bottled product. Specify red, white, or green. If you would like a 750ml bottle cover, please send an email to Tobita as a custom product.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const doilies = [
    {
        id: 1,
        title: "Ruffled Doily",
        img: "img/ruffleddoily.jpg",
        price: 50,
        info:"Beautiful ruffled doily to protect your furniture or fine porcelain. Measures approximately 12 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Rose Oval Doily",
        img: "img/roseoval.jpg",
        price: 55,
        info:"A Beautiful Rose Oval Doily measuring 21 x 17 inches.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Pineapple Doily",
        img: "img/lgpineapple.jpg",
        price: 45,
        info:"This Pineapple Doily fits perfectly on top of table top measuring 20 inches round. Looks absolutely gorgeous on top of a table topper with contrasting color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Tiny Rectangular Doily",
        img: "img/tinyrectdoily.jpg",
        price: 5,
        info:"This is a small little rectangular doily that measures approximately 5 1/2 x 4 1/2 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Blue & Yellow Pansy Doily",
        img: "img/blueyellowpansy.jpg",
        price: 30,
        info:"Beautiful pansy doily to protect your furniture or fine porcelain. Measures approximately 10 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "White Doily",
        img: "img/doily1.jpg",
        price: 25,
        info:"Beautiful doily to protect your furniture or fine porcelain. Measures 7 inches across. Specify white or ecru color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        title: "Victorian Rose Doily",
        img: "img/doily10.jpg",
        price: 30,
        info:"Beautiful Victorian Rose doily to protect your furniture or fine porcelain. Measures 10 1/2 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 8,
        title: "Lavender Pansy Doily",
        img: "img/purplepansy.jpg",
        price: 30,
        info:"Beautiful pansy doily to protect your furniture or fine porcelain. Measures approximately 10 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9,
        title: "Small Doily",
        img: "img/doily3.jpg",
        price: 15,
        info:"Beautiful small doily to protect your furniture or fine porcelain. Measures 5 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10,
        title: "Lavender Doily",
        img: "img/doily2.jpg",
        price: 28,
        info:"Beautiful lavender doily to protect your furniture or fine porcelain. Measures 7 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 11,
        title: "Rose Doily",
        img: "img/rosedoily.jpg",
        price: 35,
        info:"Measures 14 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 12,
        title: "Hexagonal Nylon Doily",
        img: "img/nylondoily.jpg",
        price: 30,
        info:"Made with Nylon thread. Measures approximately 22 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 13,
        title: "Les Fleur Doily",
        img: "img/lfdoily.jpg",
        price: 40,
        info:"Measures approximately 16 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 14,
        title: "Butterfly Placemat Doily",
        img: "img/butterfly.jpg",
        price: 45,
        info:"Beautiful Butterfly placemat doily to entertain your guests or use it to protect your furniture or fine porcelain. Measures approximately 18 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 15,
        title: "Furniture Runner Doilies",
        img: "img/longrunner.jpg",
        price: 0,
        info:"Beautiful furniture runner doilies to protect your furniture from dust and scratches. Please send Tobita an email regarding prices. The price ranges from $25.00 to $75.00 depending on the size. Using the same motif style, these runners can be made in multiples of 5 inches or 6 inches.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 16,
        title: "Star Doily",
        img: "img/doily4.jpg",
        price: 35,
        info:"Beautiful Star Doily to protect your furniture or fine porcelain. Measures approx 16 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }

];

export const fashionDoll = [
    {
        id: 1,
        title: "Fashion Doll Furniture - no pillows",
        img: "img/barbiefurniture.jpg",
        price: 45,
        info:"Include this beautiful set to your doll collection. Set includes Settee, Chair, and Coffee Table.",
        credits: "Pattern by Annies Attic",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Fashion Doll Furniture - with pillows",
        img: "img/barbiefurniture.jpg",
        price: 50,
        info:"Include this beautiful set to your doll collection. Set includes Settee, Chair, and Coffee Table.",
        credits: "Pattern by Annies Attic",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Fashion Doll Bedroom Set",
        img: "img/bedroomset.jpg",
        price: 100,
        info:"This beautiful bedroom set includes all the things you see in the picture.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Fashion Doll Sundress",
        img: "img/fdsundress.jpg",
        price: 25,
        info:"This beautiful Sundress fits most 11 1/2 inch Fashion Dolls. Doll not included.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Fashion Doll Dress",
        img: "img/fdcasual.jpg",
        price: 35,
        info:"This beautiful casual dress fits most 11 1/2 inch Fashion Dolls. Doll not included.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Fashion Doll Gown",
        img: "img/bluegowndoll.jpg",
        price: 45,
        info:"This beautiful gown has tulle underskirt and fits most 11 1/2 inch Fashion Dolls. Doll not included.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const homeAccessories = [
    {
        id: 1,
        title: "Crochet Heart Picture Frames",
        img: "img/heartframes.jpg",
        price: 35,
        info:"Beautiful picture frame with a Crochet Heart edging to proudly display your favorite picture. Frame size is 5 x 7 and frame is included. Specify color and heart color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Mama's Washcloths - Set of 9",
        img: "img/washcloths.jpg",
        price: 55,
        info:"Each washcloth measures approximately 9 X 9 inches, square.",
        credits: "Designed by Felted Button.",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Mama's Striped Washcloths - set of 3",
        img: "img/washcloths2.jpg",
        price: 25,
        info:"Each washcloth measures approximately 9 X 9 inches, square.",
        credits: "Designed by Felted Button.",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Tablet Cover",
        img: "img/ipadcover.jpg",
        price: 20,
        info:"Protect your digital tablet with a crochet cover.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Daisy Flower Bookmarks",
        img: "img/flowerbookmarks.jpg",
        price: 10,
        info:"Use this beautiful Daisy Bookmark in your favorite book. Measures approximately 5 to 6 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Flower Edge Table Topper",
        img: "img/tabletopper.jpg",
        price: 75,
        info:"Beautiful flower edged table topper to proudly display your table top ornaments. The flowers will vary depending on availability. Specify white or ecru color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        title: "Bathroom Set",
        img: "img/bathroomset.jpg",
        price: 50,
        info:"Beautiful Bathroom Set to beautify your bathroom.   Set includes toilet tissue cover, toilet tank cover, and wastebasket cover.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 8,
        title: "Remote Control Holder - Two Pockets",
        img: "img/twopocketremote.jpg",
        price: 25,
        info:"Keep those remotes in the right place without having to worry where they are. This Remote Control Holder fits over the sofa arm and is machine washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9,
        title: "Remote Control Holder - Three Pockets",
        img: "img/remoteholder.jpg",
        price: 30,
        info:"Keep those remotes in the right place without having to worry where they are. This Remote Control Holder fits over the sofa arm and is machine washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10,
        title: "Curtain Tiebacks - Pair",
        img: "img/tieback.jpg",
        price: 15,
        info:"Curtain Tiebacks measuring 2 inches wide and 14 inches in length.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 11,
        title: "Valance",
        img: "img/valance2.jpg",
        price: 95,
        info:"Beautiful valance to cover your window, measuring 48 - 52 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 12,
        title: "Napkin Rings - Set of 8",
        img: "img/napkinholders.jpg",
        price: 30,
        info:"Fan style cloth napkin rings. Measures 3 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 13,
        title: "Tissue Roll Cover",
        img: "img/trollcover1.jpg",
        price: 20,
        info:"Enhance your decor with this elegant tissue cover. Machine Washable and Dryable. Specify the main and contrasting colors (double size tissue roll included).",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 14,
        title: "Facial Tissue Box Cover",
        img: "img/tboxcover1.jpg",
        price: 20,
        info:"Beautify your room with this crochet tissue cover. Machine Washable and Dryable. Specify your main and contrasting colors (Box of tissue included).",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 15,
        title: "Oval Rug",
        img: "img/rug.jpg",
        price: 35,
        info:"Measures 24 x 36 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const kidsStuff = [
    {
        id: 1,
        title: "Child's Ladybug Backpack",
        img: "img/ladybugbackpack.jpg",
        price: 65,
        info:"Any child would enjoy this cute Ladybug Backpack! The backpack measures approximately 10 inches across. It's perfect for the little one to carry their little things.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Hello Kitty Doll",
        img: "img/hellokitty.jpg",
        price: 40,
        info:"",
        credits: "Hello Kitty Pattern Grukhina.ru",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Tutu Cute Ballet Bag",
        img: "img/tutuballetbag.jpg",
        price: 70,
        info:"Any little girl would enjoy this cute TuTu bag for her ballet. Measures 10 x 10 inches excluding the handle.",
        credits: "Designed by Carrie Carpenter, Love of Crochet|Weekend Crochet 2013.",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Crochet Clown",
        img: "img/clown.jpg",
        price: 45,
        info:"Any child would enjoy this cute Clown! Measures 17 inches high. For the color, choose the main body color or if you like the same one, type in same.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Miniature Bear",
        img: "img/minibear.jpg",
        price: 35,
        info:"A cute little miniature bear measuring 4.5 cm which is less than 2 inches high.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Bear with Dress",
        img: "img/dressbear1.jpg",
        price: 25,
        info:"Eyes are sewn and glued for child safety. Washable and Dryable. Measures approximately 7 inches tall. Specify dress and bear color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        title: "Bears",
        img: "img/bears.jpg",
        price: 18,
        info:"Eyes are sewn and glued for child safety. Measures approximately 7 inches tall.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 8,
        title: "Canadian Mountie Doll",
        img: "img/mountie.jpg",
        price: 40,
        info:"Measures approximately 18 inches tall.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9,
        title: "Bear with Shorts",
        img: "img/boybear.jpg",
        price: 25,
        info:"Measures approximately 7 inches tall. Specify shorts and bear color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10,
        title: "Stuffed Dolphin Toy",
        img: "img/dolfin.jpg",
        price: 20,
        info:"Stuffed Dolphin Toy measuring approximately 11 inches long and 2 1/2 inches body width. Eyes are sewed and glued for child-proof protection. Specify white or gray color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 11,
        title: "Cone-shaped Air Freshener Doll Cover",
        img: "img/doll.jpg",
        price: 30,
        info:"Cone shaped doll to cover an air freshener or use it to decorate any room in your home. Measures approximately 10 inches tall with hat.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const kitchen = [
    {
        id: 1,
        title: "Crochet Hot Pad with Fabric Edging",
        img: "img/pthldr.jpg",
        price: 18,
        info:"A wonderful hot pad to have for your kitchen.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Frog Hot Pad",
        img: "img/froghotpad.jpg",
        price: 25,
        info:"A wonderful hot pad to have for your kitchen.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Frog Oven Mitt",
        img: "img/frogovenmitt.jpg",
        price: 25,
        info:"A frog oven mitt to match the hot pad.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Frog Towel Topper",
        img: "img/frogtoweltopper2.jpg",
        price: 30,
        info:"Frog towel topper to match the hot pad and oven mitt.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const mensWear = [
    {
        id: 1,
        title: "Mens Crochet Sweater",
        img: "img/mensweater.jpg",
        price: 150,
        info:"Hand Crochet mens sweater made with wool and acrylic yarn.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Mens Crochet Tie",
        img: "img/tie.jpg",
        price: 30,
        info:"This handmade crocheted tie goes great with any shirt or suit.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const patriotic = [
    {
        id: 1,
        title: "Patriotic Angel",
        img: "img/patangel.jpg",
        price: 45,
        info:"Display your patriotism by adding this beautiful Patriotic Angel in your home.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Star Spangled Fashion Doll",
        img: "img/starspangleddoll.jpg",
        price: 25,
        info:"Display your patriotism by adding this beautiful Patriotic Star Spangled Fashion Doll in your home. Not recommended for children under 10 years old. It is more for display purposes only. Sequins and stars are glued on the outfit and fits most 11 1/2 inch Fashion Dolls. Doll not included.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0
    }
];

export const storeProducts = [
    {
        id: 1,
        title: "Stained Glass Afghan",
        img: "img/stainedglassafghan.jpg",
        price: 150,
        info:"Measures approximately 45 x 60 inches.",
        credits: "Pattern Source: Annie's Crochet 885109",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 2,
        title: "Peace Sign Afghan",
        img: "img/peacesignafghan.jpg",
        price: 140,
        info:"Measures approximately 48 x 70 inches.",
        credits: "Designed by JudyK - Published in So Far, So Good.",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 3,
        title: "Zebra Afghan",
        img: "img/zebraafghan.jpg",
        price: 200,
        info:"Measures approximately 46 x 61 inches.",
        credits: "Pattern Source: Annie's Crochet Newsletter Nov-Dec 1990",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 4,
        title: "Kaleidoscope Eyes Blanket",
        img: "img/kaleidoscopeeyesblanket.jpg",
        price: 130,
        info:"Measures approximately 39 x 51 inches.",
        credits: "Designed by FeltedButton.com",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 5,
        title: "Christmas Afghan",
        img: "img/Christmas Afghan.jpg",
        price: 100,
        info:"Measures approximately 56 x 72 inches.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 6,
        title: "Basketweave Afghan",
        img: "img/basketweaveafghan.jpg",
        price: 145,
        info:"Afghan in a Basketweave pattern. It is a little bit heavier than the regular afghans.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 7,
        title: "Climbing Rose Lace Afghan",
        img: "img/climbingroseafghan.jpg",
        price: 175,
        info:"This afghan has lacy edges and panels. The rosebuds, stems, and leaves are embroidered on the afghan. Please specify the main color as white or off-white with your rose color preference.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 8,
        title: "Big Granny Square Afghan",
        img: "img/biggranny.jpg",
        price: 95,
        info:"This afghan has large and small squares to make this perfect Granny afghan.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 9,
        title: "Pineapple Square Afghan",
        img: "img/pineapplesquareafghan.jpg",
        price: 100,
        info:"Measures approximately 56 x 72 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 10,
        title: "Red and White Wavy Lapghan",
        img: "img/redandwhiteafghan.jpg",
        price: 85,
        info:"Measures approximately 36 x 54 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 11,
        title: "Peruvian Style Afghan",
        img: "img/peruvianstyleafghan.jpg",
        price: 125,
        info:"This is a simple Peruvian style afghan measuring 45 x 72 inches. Size can be adjusted by width or length. For custom size, send an email to Tobita. Additional charge for bigger size afghan will apply.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 12,
        title: "Irish Afghan",
        img: "img/aran_afghan.jpg",
        price: 145,
        info:"Measures approximately 45 x 85 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 13,
        title: "Granny Square Throw",
        img: "img/grannysquareafghan.jpg",
        price: 95,
        info:"Measures approximately 38 x 58 inches. A perfect throw to lounge and snuggle up with. Please specify color(s).",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 14,
        title: "Ripple Afghan",
        img: "img/ripple.jpg",
        price: 120,
        info:"Measures approximately 42 x 72 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 15,
        title: "Fisherman Ripple Afghan",
        img: "img/afghan.jpg",
        price: 120,
        info:"This Afghan is almost the same as the Black and Grey afghan except this one has some lacy effects in between some solid rows. Afghan measures approximately 48 x 75 inches, slightly longer than the Ripple Afghan.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 16,
        title: "Popcorn Diamond Square - Afghan",
        img: "img/bed.jpg",
        price: 150,
        info:"This type of afghan can be made custom size. The sample in the picture was made as a bedcover. The measurement for a regular size afghan is approximately 55 x 84 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 17,
        title: "Circle of Squares Lapghan",
        img: "img/circlesquareafghan.jpg",
        price: 95,
        info:"This is a smaller afghan which measures approximately 38 x 54 inches.  The squares are in different colors...makes a wonderful gift!",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 18,
        title: "Pink Cluster Afghan",
        img: "img/pinkafghan1.jpg",
        price: 125,
        info:"Afghan measures approximately 48 x 72 inches. Can be crocheted in any color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 19,
        title: "Simplistic Afghan",
        img: "img/yellowpinkafghan.jpg",
        price: 110,
        info:"Measures approximately 48 x 60 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 20,
        title: "Scrap Afghan",
        img: "img/scrapafghan.jpg",
        price: 100,
        info:"This afghan is crocheted with leftover yarn from other projects to create beautiful color cordinated squares. Afghan measures approximately 48 x 60 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
      },
      {
        id: 21,
        title: "Popcorn Diamond Square - Bedcover",
        img: "img/bed.jpg",
        price: 200,
        info:"This type of bedcover can be made custom size. The sample in the picture was made as a bedcover. $25-$75 additional charge for larger bed sizes. Email for quote",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Bedcovers"
      },
      {
        id: 22,
        title: "Flower Square Bedcover",
        img: "img/bedcover.jpg",
        price: 250,
        info:"Crocheted with 100% mercerized cotton thread. $50-$100 additional for larger bed size. Email for quote.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Bedcovers"
    },
    {
        id: 23,
        title: "Multi Pastel Color Baby Afghan - LG",
        img: "img/babyafghan.jpg",
        price: 65,
        info:"Measures 40x50 inches. This baby afghan is crocheted with variegated baby pastel colors. If you want a solid color, please insert your color preference in the color box.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 24,
        title: "Multi Pastel Color Baby Afghan - SM",
        img: "img/babyafghan.jpg",
        price: 60,
        info:"Measures 36x48 inches. This baby afghan is crocheted with variegated baby pastel colors. If you want a solid color, please insert your color preference in the color box.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 25,
        title: "Feathery Lace Baby Afghan",
        img: "img/featherylacebabyghan.jpg",
        price: 60,
        info:"Measures 38 1/2 x 52 inches. Washable and dryable.",
        credits: "Pattern Source: Ripples for Baby to Crochet by Leisure Arts",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 26,
        title: "Football and Baby Name Baby Afghan",
        img: "img/namefootball.jpg",
        price: 70,
        info:"Baby afghan with a football and your baby's name. You can leave out the football and have only your baby's name on the afghan. Measures approximately 36 x 48 inches (depending on the length of the name). Washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 27,
        title: "Small Squares Baby Afghan",
        img: "img/bsqafghan.jpg",
        price: 60,
        info:"This cute little baby afghan is crocheted with lots of tiny squares. Measures 32 x 44 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 28,
        title: "Pink & White Baby Afghan",
        img: "img/pinkbafghan.jpg",
        price: 60,
        info:"Measures approximately 36 x 48 inches. Washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 29,
        title: "Pink & White Baby Afghan - With Booties",
        img: "img/pinkbafghan.jpg",
        price: 65,
        info:"Measures approximately 36 x 48 inches. Washable and dryable. Includes pair of baby booties in matching color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 30,
        title: "Blue & White Baby Afghan",
        img: "img/blanket.jpg",
        price: 60,
        info:"Measures approximately 36 x 48 inches. Washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 31,
        title: "Blue & White Baby Afghan - With Booties",
        img: "img/blanket.jpg",
        price: 65,
        info:"Measures approximately 36 x 48 inches. Washable and dryable. Includes pair of baby booties in matching color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 32,
        title: "Crocheted Star Baby Quilt",
        img: "img/quilt.jpg",
        price: 90,
        info:"Baby afghan is crocheted and sewn like a real quilt! Measurements are approximately 36 x 48 inches. Washable and Dryable.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 33,
        title: "Rainbow Baby Afghan",
        img: "img/rainbow.jpg",
        price: 85,
        info:"Rainbows in a baby afghan.",
        credits: "Pattern design by Helen Free",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 34,
        title: "Granny Square Style Baby Afghan",
        img: "img/bluegrannybabyghan.jpg",
        price: 70,
        info:"Measures approximately 36 x 38 inches. Machine washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 35,
        title: "Baby Afghan",
        img: "img/blnktbr.jpg",
        price: 60,
        info:"Measures approximately 36 x 48 inches. Machine washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 36,
        title: "Baby Afghan - with Bear",
        img: "img/blnktbr.jpg",
        price: 70,
        info:"Measures approximately 36 x 48 inches. Machine washable and dryable. Includes teddy bear in matching color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Afghans"
    },
    {
        id: 37,
        title: "Baby Boy Outfit",
        img: "img/babyboyoutfit.jpg",
        price: 75,
        info:"A beautiful set for a Baby Boy. Set includes Pants, Sweater, Booties, and bonnett.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 38,
        title: "Open Crescent Baby Dress",
        img: "img/threadbabydress.jpg",
        price: 75,
        info:"A beautiful Pineapple Baby dress with open crescent skirt.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 39,
        title: "Pineapple Dress and Beret",
        img: "img/pineappledress.jpg",
        price: 95,
        info:"A beautiful Pineapple Baby dress with buttoned-back opening and beret.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 40,
        title: "Baby Tank Top and Undies",
        img: "img/babytankundies.jpg",
        price: 65,
        info:"A tank top and undies to use under a formal dress, pineapple dress, or use it alone.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 41,
        title: "Tiny Square Yoke Dress and Booties",
        img: "img/b-dress.jpg",
        price: 70,
        info:"See matching booties in Baby Shoes section.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 42,
        title: "Filet Baby Dress and Booties",
        img: "img/filetdress.jpg",
        price: 65,
        info:"Crocheted with fine cotton thread for those hot summer months.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 43,
        title: "Baby Layette Set",
        img: "img/babyset.jpg",
        price: 85,
        info:"Set includes Baby Afghan, Baby Sweater, and Baby Booties.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 44,
        title: "Two Color Dress and Booties",
        img: "img/ls-dress.jpg",
        price: 85,
        info:"Specify Top color and Skirt color",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 45,
        title: "Pants & Sweater Combo",
        img: "img/pants_sweater.jpg",
        price: 65,
        info:"A comfortable drawstring pants and buttoned front sweater.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 46,
        title: "Formal Baby Dress and Booties",
        img: "img/bwdress.jpg",
        price: 70,
        info:"A formal crochet dress with buttoned-back opening, underskirt fabric lining, and baby booties.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Clothes"
    },
    {
        id: 47,
        title: "Heart Embedded Baby Booties",
        img: "img/heartbabyshoes.jpg",
        price: 25,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Booties"
    },
    {
        id: 48,
        title: "Girl Skate Booties",
        img: "img/girlskates.jpg",
        price: 35,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Booties"
    },
    {
        id: 49,
        title: "Boy Skate Booties",
        img: "img/boyskates.gif",
        price: 35,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Booties"
    },
    {
        id: 50,
        title: "Baby Booties",
        img: "img/bshoes.jpg",
        price: 20,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Booties"
    },
    {
        id: 51,
        title: "Tiny Square Yoke Baby Booties",
        img: "img/bbyshoe3.jpg",
        price: 25,
        info:"",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Baby Booties"
    },
    {
        id: 52,
        title: "Bridal Set",
        img: "img/bridalset.jpg",
        price: 95,
        info:"Beautiful Bridal set for the new Bride. Set includes Garter, Purse, Horseshoe, Ring Pillow, and Choker. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004. Pattern for sale at http://www.enfys.dsl.pipex.com",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Bridal"
    },
    {
        id: 53,
        title: "Bridal Garter",
        img: "img/bridalgarter.jpg",
        price: 25,
        info:"Beautiful Bridal Garter for the bride. Garter is made with glittery seed beads to give it the classy elegant look. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Bridal"
    },
    {
        id: 54,
        title: "Bridal Ring Pillow",
        img: "img/bridalringpillow.jpg",
        price: 25,
        info:"The Bridal Ring Pillow holds the couple's wedding rings. Made with glossy seed beads and satin fabric to give the pillow a classy elegant look. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Bridal"
    },
    {
        id: 55,
        title: "Bridal Choker",
        img: "img/bridalchoker.jpg",
        price: 20,
        info:"Choker is made with glossy beads and ribbon for that classy elegant look. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Bridal"
    },
    {
        id: 56,
        title: "Bridal Purse",
        img: "img/bridalpurse.jpg",
        price: 30,
        info:"Beautiful Bridal purse for the new Bride. Made with glossy seed beads and lined with satin fabric. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Bridal"
    },
    {
        id: 57,
        title: "Bridal Horseshoe",
        img: "img/bridalhorseshoe.jpg",
        price: 25,
        info:"Start your tradition by giving the Bride a Horse Shoe for luck and fortune. Made with seed beads and ribbon. Specify white or off-white color.",
        credits: "Designed by Helen Free, 2004.",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Bridal"
    },
    {
        id: 58,
        title: "Christmas Stocking",
        img: "img/bootstocking.jpg",
        price: 15,
        info:"Measures 16 inches in height. Beautiful Stocking to add to your Christmas decorations and holds lots of goodies! Specify main color and heel color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 59,
        title: "Crochet Christmas Creche",
        img: "img/crochetcreche.jpg",
        price: 95,
        info:"Measures from 3 to 9 inches in height. Beautiful Mary, Joseph, and Child Jesus set with animals to add to your Christmas display.",
        credits: "Pattern purchased from Annie's e-pattern central.",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 60,
        title: "Christmas Tree Skirt",
        img: "img/christmastreeskirt.jpg",
        price: 65,
        info:"Measures approximately 36 inches across.",
        credits: "Pattern from Love the Country website.",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 61,
        title: "Christmas Wreath",
        img: "img/christmaswreath.jpg",
        price: 85,
        info:"Measures approximately 14 inches across.",
        credits: "Pattern by Attic24",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 62,
        title: "Snowman",
        img: "img/snowman.jpg",
        price: 5,
        info:"Measures 4 inches in height. Beautiful ornament to add to your Christmas decorations.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 63,
        title: "Angel in Gold Dress",
        img: "img/gold-angel.jpg",
        price: 35,
        info:"Beautiful angel in a gold dress. Can be used as a tree topper or place anywhere in the home. Measures approximately 7 inches tall.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 64,
        title: "White Mini-Angel Tree Ornament",
        img: "img/miniangels.jpg",
        price: 1,
        info:"Measures approximately 3 inches in height.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 65,
        title: "Candy Cane Tree Ornament",
        img: "img/candycane.jpg",
        price: .75,
        info:"Measures approximately 3 inches in height. Specify red, white, or Christmas color blend.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 66,
        title: "Christmas Tree",
        img: "img/g-tree.jpg",
        price: 15,
        info:"Measures approximately 7 inches tall. Decorated with available mini ornaments. Specify tree and bow color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 67,
        title: "Angel",
        img: "img/angel2.jpg",
        price: 25,
        info:"This beautiful angel looks beautiful on top of the Christmas Tree or anywhere in your house. Measures approximately 7 inches tall. Specify dress and hair color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 68,
        title: "Mini Christmas Booties",
        img: "img/booties.jpg",
        price: 3,
        info:"Measures approximately 4 inches tall. Specify color. Buy two, get $1 off!",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 69,
        title: "Mini Christmas Baskets",
        img: "img/w-basket.jpg",
        price: 3,
        info:"Measures approximately 3 inches tall. Specify color. Buy two, get $1 off!",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 70,
        title: "Christmas Jingle Bells",
        img: "img/christmas-bells.jpg",
        price: 3,
        info:"Measures approximately 3 inches tall. Specify color. Buy two, get $1 off!",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 71,
        title: "Wine Christmas Covering",
        img: "img/christmaswinebottlecovers.jpg",
        price: 15,
        info:"Makes a wonderful impersonal gift. Measures approximately 7 inches high. Includes wine or it can be replaced with other similar bottled product. Specify red, white, or green. If you would like a 750ml bottle cover, please send an email to Tobita as a custom product.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Christmas"
    },
    {
        id: 72,
        title: "Ruffled Doily",
        img: "img/ruffleddoily.jpg",
        price: 50,
        info:"Beautiful ruffled doily to protect your furniture or fine porcelain. Measures approximately 12 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 73,
        title: "Rose Oval Doily",
        img: "img/roseoval.jpg",
        price: 55,
        info:"A Beautiful Rose Oval Doily measuring 21 x 17 inches.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 74,
        title: "Pineapple Doily",
        img: "img/lgpineapple.jpg",
        price: 45,
        info:"This Pineapple Doily fits perfectly on top of table top measuring 20 inches round. Looks absolutely gorgeous on top of a table topper with contrasting color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 75,
        title: "Tiny Rectangular Doily",
        img: "img/tinyrectdoily.jpg",
        price: 5,
        info:"This is a small little rectangular doily that measures approximately 5 1/2 x 4 1/2 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 76,
        title: "Blue & Yellow Pansy Doily",
        img: "img/blueyellowpansy.jpg",
        price: 30,
        info:"Beautiful pansy doily to protect your furniture or fine porcelain. Measures approximately 10 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 77,
        title: "White Doily",
        img: "img/doily1.jpg",
        price: 25,
        info:"Beautiful doily to protect your furniture or fine porcelain. Measures 7 inches across. Specify white or ecru color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 78,
        title: "Victorian Rose Doily",
        img: "img/doily10.jpg",
        price: 30,
        info:"Beautiful Victorian Rose doily to protect your furniture or fine porcelain. Measures 10 1/2 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 79,
        title: "Lavender Pansy Doily",
        img: "img/purplepansy.jpg",
        price: 30,
        info:"Beautiful pansy doily to protect your furniture or fine porcelain. Measures approximately 10 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 80,
        title: "Small Doily",
        img: "img/doily3.jpg",
        price: 15,
        info:"Beautiful small doily to protect your furniture or fine porcelain. Measures 5 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 81,
        title: "Lavender Doily",
        img: "img/doily2.jpg",
        price: 28,
        info:"Beautiful lavender doily to protect your furniture or fine porcelain. Measures 7 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 82,
        title: "Rose Doily",
        img: "img/rosedoily.jpg",
        price: 35,
        info:"Measures 14 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 83,
        title: "Hexagonal Nylon Doily",
        img: "img/nylondoily.jpg",
        price: 30,
        info:"Made with Nylon thread. Measures approximately 22 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 84,
        title: "Les Fleur Doily",
        img: "img/lfdoily.jpg",
        price: 40,
        info:"Measures approximately 16 inches across.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 85,
        title: "Butterfly Placemat Doily",
        img: "img/butterfly.jpg",
        price: 45,
        info:"Beautiful Butterfly placemat doily to entertain your guests or use it to protect your furniture or fine porcelain. Measures approximately 18 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 86,
        title: "Furniture Runner Doilies",
        img: "img/longrunner.jpg",
        price: 60,
        info:"Beautiful furniture runner doilies to protect your furniture from dust and scratches. Please send Tobita an email regarding prices. The price ranges from $25.00 to $75.00 depending on the size. Using the same motif style, these runners can be made in multiples of 5 inches or 6 inches.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 87,
        title: "Star Doily",
        img: "img/doily4.jpg",
        price: 35,
        info:"Beautiful Star Doily to protect your furniture or fine porcelain. Measures approx 16 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Doilies"
    },
    {
        id: 88,
        title: "Fashion Doll Furniture - no pillows",
        img: "img/barbiefurniture.jpg",
        price: 45,
        info:"Include this beautiful set to your doll collection. Set includes Settee, Chair, and Coffee Table.",
        credits: "Pattern by Annies Attic",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Fashion Doll"
    },
    {
        id: 89,
        title: "Fashion Doll Furniture - with pillows",
        img: "img/barbiefurniture.jpg",
        price: 50,
        info:"Include this beautiful set to your doll collection. Set includes Settee, Chair, and Coffee Table.",
        credits: "Pattern by Annies Attic",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Fashion Doll"
    },
    {
        id: 90,
        title: "Fashion Doll Bedroom Set",
        img: "img/bedroomset.jpg",
        price: 100,
        info:"This beautiful bedroom set includes all the things you see in the picture.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Fashion Doll"
    },
    {
        id: 91,
        title: "Fashion Doll Sundress",
        img: "img/fdsundress.jpg",
        price: 25,
        info:"This beautiful Sundress fits most 11 1/2 inch Fashion Dolls. Doll not included.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Fashion Doll"
    },
    {
        id: 92,
        title: "Fashion Doll Dress",
        img: "img/fdcasual.jpg",
        price: 35,
        info:"This beautiful casual dress fits most 11 1/2 inch Fashion Dolls. Doll not included.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Fashion Doll"
    },
    {
        id: 93,
        title: "Fashion Doll Gown",
        img: "img/bluegowndoll.jpg",
        price: 45,
        info:"This beautiful gown has tulle underskirt and fits most 11 1/2 inch Fashion Dolls. Doll not included.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Fashion Doll"
    },
    {
        id: 94,
        title: "Crochet Heart Picture Frames",
        img: "img/heartframes.jpg",
        price: 35,
        info:"Beautiful picture frame with a Crochet Heart edging to proudly display your favorite picture. Frame size is 5 x 7 and frame is included. Specify color and heart color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 95,
        title: "Mama's Washcloths - Set of 9",
        img: "img/washcloths.jpg",
        price: 55,
        info:"Each washcloth measures approximately 9 X 9 inches, square.",
        credits: "Designed by Felted Button.",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 96,
        title: "Mama's Striped Washcloths - set of 3",
        img: "img/washcloths2.jpg",
        price: 25,
        info:"Each washcloth measures approximately 9 X 9 inches, square.",
        credits: "Designed by Felted Button.",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 97,
        title: "Tablet Cover",
        img: "img/ipadcover.jpg",
        price: 20,
        info:"Protect your digital tablet with a crochet cover.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 98,
        title: "Daisy Flower Bookmarks",
        img: "img/flowerbookmarks.jpg",
        price: 10,
        info:"Use this beautiful Daisy Bookmark in your favorite book. Measures approximately 5 to 6 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 99,
        title: "Flower Edge Table Topper",
        img: "img/tabletopper.jpg",
        price: 95,
        info:"Beautiful flower edged table topper to proudly display your table top ornaments. The flowers will vary depending on availability. Specify white or ecru color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 100,
        title: "Bathroom Set",
        img: "img/bathroomset.jpg",
        price: 50,
        info:"Beautiful Bathroom Set to beautify your bathroom.   Set includes toilet tissue cover, toilet tank cover, and wastebasket cover.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 101,
        title: "Remote Control Holder - Two Pockets",
        img: "img/twopocketremote.jpg",
        price: 25,
        info:"Keep those remotes in the right place without having to worry where they are. This Remote Control Holder fits over the sofa arm and is machine washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 102,
        title: "Remote Control Holder - Three Pockets",
        img: "img/remoteholder.jpg",
        price: 30,
        info:"Keep those remotes in the right place without having to worry where they are. This Remote Control Holder fits over the sofa arm and is machine washable and dryable.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 103,
        title: "Curtain Tiebacks - Pair",
        img: "img/tieback.jpg",
        price: 15,
        info:"Curtain Tiebacks measuring 2 inches wide and 14 inches in length.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 104,
        title: "Valance",
        img: "img/valance2.jpg",
        price: 95,
        info:"Beautiful valance to cover your window, measuring 48 - 52 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 105,
        title: "Napkin Rings - Set of 8",
        img: "img/napkholders.jpg",
        price: 30,
        info:"Fan style cloth napkin rings. Measures 3 inches across.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 106,
        title: "Tissue Roll Cover",
        img: "img/trollcover1.jpg",
        price: 20,
        info:"Enhance your decor with this elegant tissue cover. Machine Washable and Dryable. Specify the main and contrasting colors (double size tissue roll included).",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 107,
        title: "Facial Tissue Box Cover",
        img: "img/tboxcover1.jpg",
        price: 20,
        info:"Beautify your room with this crochet tissue cover. Machine Washable and Dryable. Specify your main and contrasting colors (Box of tissue included).",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 108,
        title: "Oval Rug",
        img: "img/rug.jpg",
        price: 35,
        info:"Measures 24 x 36 inches.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Home Accessories"
    },
    {
        id: 109,
        title: "Child's Ladybug Backpack",
        img: "img/ladybugbackpack.jpg",
        price: 65,
        info:"Any child would enjoy this cute Ladybug Backpack! The backpack measures approximately 10 inches across. It's perfect for the little one to carry their little things.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 110,
        title: "Hello Kitty Doll",
        img: "img/hellokitty.jpg",
        price: 40,
        info:"",
        credits: "Hello Kitty Pattern Grukhina.ru",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 111,
        title: "Tutu Cute Ballet Bag",
        img: "img/tutuballetbag.jpg",
        price: 70,
        info:"Any little girl would enjoy this cute TuTu bag for her ballet. Measures 10 x 10 inches excluding the handle.",
        credits: "Designed by Carrie Carpenter, Love of Crochet|Weekend Crochet 2013.",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 112,
        title: "Crochet Clown",
        img: "img/clown.jpg",
        price: 45,
        info:"Any child would enjoy this cute Clown! Measures 17 inches high. For the color, choose the main body color or if you like the same one, type in same.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 113,
        title: "Miniature Bear",
        img: "img/minibear.jpg",
        price: 35,
        info:"A cute little miniature bear measuring 4.5 cm which is less than 2 inches high.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 114,
        title: "Bear with Dress",
        img: "img/dressbear1.jpg",
        price: 25,
        info:"Eyes are sewn and glued for child safety. Washable and Dryable. Measures approximately 7 inches tall. Specify dress and bear color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 115,
        title: "Bears",
        img: "img/bears.jpg",
        price: 18,
        info:"Eyes are sewn and glued for child safety. Measures approximately 7 inches tall.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 116,
        title: "Canadian Mountie Doll",
        img: "img/mountie.jpg",
        price: 40,
        info:"Measures approximately 18 inches tall.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 117,
        title: "Bear with Shorts",
        img: "img/boybear.jpg",
        price: 25,
        info:"Measures approximately 7 inches tall. Specify shorts and bear color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 118,
        title: "Stuffed Dolphin Toy",
        img: "img/dolfin.jpg",
        price: 20,
        info:"Stuffed Dolphin Toy measuring approximately 11 inches long and 2 1/2 inches body width. Eyes are sewed and glued for child-proof protection. Specify white or gray color.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 119,
        title: "Cone-shaped Air Freshener Doll Cover",
        img: "img/doll.jpg",
        price: 30,
        info:"Cone shaped doll to cover an air freshener or use it to decorate any room in your home. Measures approximately 10 inches tall with hat.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kids Stuff"
    },
    {
        id: 120,
        title: "Crochet Hot Pad with Fabric Edging",
        img: "img/pthldr.jpg",
        price: 18,
        info:"A wonderful hot pad to have for your kitchen.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kitchen"
    },
    {
        id: 121,
        title: "Frog Hot Pad",
        img: "img/froghotpad.jpg",
        price: 25,
        info:"A wonderful hot pad to have for your kitchen.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kitchen"
    },
    {
        id: 122,
        title: "Frog Oven Mitt",
        img: "img/frogovenmitt.jpg",
        price: 25,
        info:"A frog oven mitt to match the hot pad.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kitchen"
    },
    {
        id: 123,
        title: "Frog Towel Topper",
        img: "img/frogtoweltopper2.jpg",
        price: 30,
        info:"Frog towel topper to match the hot pad and oven mitt.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Kitchen"
    },
    {
        id: 124,
        title: "Mens Crochet Sweater",
        img: "img/mensweater.jpg",
        price: 150,
        info:"Hand Crochet mens sweater made with wool and acrylic yarn.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Mens Wear"
    },
    {
        id: 125,
        title: "Mens Crochet Tie",
        img: "img/tie.jpg",
        price: 30,
        info:"This handmade crocheted tie goes great with any shirt or suit.",
        credits: "",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Mens Wear"
    },
    {
        id: 126,
        title: "Patriotic Angel",
        img: "img/patangel.jpg",
        price: 45,
        info:"Display your patriotism by adding this beautiful Patriotic Angel in your home.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Patriotic"
    },
    {
        id: 127,
        title: "Star Spangled Fashion Doll",
        img: "img/starspangleddoll.jpg",
        price: 25,
        info:"Display your patriotism by adding this beautiful Patriotic Star Spangled Fashion Doll in your home. Not recommended for children under 10 years old. It is more for display purposes only. Sequins and stars are glued on the outfit and fits most 11 1/2 inch Fashion Dolls. Doll not included.",
        credits: "",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Patriotic"
    },
    {
        id: 128,
        title: "Dark Green Fashion Doll Furniture Set",
        img: "img/darkgreenfurn.jpg",
        price: 35,
        info:"This set includes Settee, Chair, and Mini table.",
        credits: "These handmade crochet items listed are available for immediate sale and shipped out the next day upon receipt of payment. Once they are sold, the items will be replaced or removed from this page.",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Web Specials"
    },
    {
        id: 129,
        title: "Mens Crochet Ties",
        img: "img/mensties.jpg",
        price: 25,
        info:"Beautiful hand crochet tie. Price listed is for one tie.",
        credits: "These handmade crochet items listed are available for immediate sale and shipped out the next day upon receipt of payment. Once they are sold, the items will be replaced or removed from this page.",
        color: true,
        inCart: false,
        count: 0,
        total: 0,
        type: "Web Specials"
    },
    
  ];
  
export const detailProduct = {
        id: 1,
        title: "Stained Glass Afghan",
        img: "img/stainedglassafghan.jpg",
        price: 150,
        info:"Measures approximately 45 x 60 inches.",
        credits: "Pattern Source: Annie's Crochet 885109",
        color: false,
        inCart: false,
        count: 0,
        total: 0,
        type: "Afghans"
  };
  